show github rate limit

diff --git a/.github/workflows/build_single_ref.yml b/.github/workflows/build_single_ref.yml
--- a/.github/workflows/build_single_ref.yml
+++ b/.github/workflows/build_single_ref.yml
@@ -105,6 +105,10 @@ jobs:
         if: failure()
         run: cat process.log || echo "No log file found"
         shell: bash
+      - run: gh api rate_limit || echo "could not get gh rate limits"
+        if: failure()
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   build:
     needs: [prepare-matrix]
@@ -179,3 +183,7 @@ jobs:
         if: failure()
         run: cat process.log || echo "No log file found"
         shell: bash
+      - run: gh api rate_limit || echo "could not get gh rate limits"
+        if: failure()
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
